CSID-DGU/2024-2-SCS4031-4tune-1

src/frontend/eyesee-admin/package.json
src/frontend/eyesee-admin/pnpm-lock.yaml
src/frontend/eyesee-admin/src/apis/dashBoard.ts
src/frontend/eyesee-admin/src/apis/examList.ts
src/frontend/eyesee-admin/src/apis/index.ts
src/frontend/eyesee-admin/src/apis/userDetail.ts
src/frontend/eyesee-admin/src/app/dashboard/[examId]/page.tsx
src/frontend/eyesee-admin/src/app/layout.tsx
src/frontend/eyesee-admin/src/app/providers.tsx
src/frontend/eyesee-admin/src/hooks/api/useDashboard.ts
src/frontend/eyesee-admin/src/hooks/api/useExamList.ts
src/frontend/eyesee-admin/src/hooks/api/useUserDetail.ts
src/frontend/eyesee-admin/src/utils/auth.ts

> #22
> API 통신을 위한 axios, tanstack query 초기 세팅을 진행하였습니다.
> get 요청의 테스트 코드도 작성하였습니다.

FE: [feature] api 통신 초기 세팅

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/config/SecurityConfig.java

> cors 화이트리스트만 수정하여 올렸습니다.
>  cors 화이트리스트만 수정하여 올렸습니다.

BE: [fix] CORS 허용 오리진 추가

---

src/frontend/eyesee-user/package.json
src/frontend/eyesee-user/pnpm-lock.yaml
src/frontend/eyesee-user/src/app/exam-room/page.tsx
src/frontend/eyesee-user/src/app/video/page.tsx
src/frontend/eyesee-user/src/components/agreement/AgreementSection.tsx
src/frontend/eyesee-user/src/components/common/NextButton.tsx
src/frontend/eyesee-user/src/hooks/useWebsocket.ts
src/frontend/eyesee-user/src/utils/websocket.ts
src/frontend/eyesee-user/tsconfig.json

> #34
> 백엔드 서버로 실시간 수험자 화면을 보내는 웹소켓 코드를 추가했습니다.

FE: [feat] 웹소켓 설정 및 빌드 에러 해결

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/controller/SessionController.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/dto/TokenWithUserIdResponseDTO.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/service/SessionService.java

> ex) #6
> 학생 세션 입장 토큰 응답 구조 수정

BE: [fix] 학생 세션 입장 토큰 응답 구조 수정 #6

---

src/ai/4tune_AI/gaze_ver2/main.py

AI: [fix] back api camelcase

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/config/SecurityConfig.java

> ex) #6
> BE: [fix] CORS 화이트리스트 수정 #6

BE: [fix] CORS 화이트리스트 수정 #6

---

src/ai/4tune_AI/gaze_ver2/main.py

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

AI: [fix] api

---

src/ai/4tune_AI/gaze_ver2/main.py

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

AI: [fix] timestamp

---

src/frontend/eyesee-user/src/app/exam-room/page.tsx
src/frontend/eyesee-user/src/components/notice/ExamCard.tsx
src/frontend/eyesee-user/src/types/exam.ts

>#66
> 수험자 유의사항 페이지 서버 정보 업데이트
> 웹소켓 연결 종료시 3초간격으로 재요청

FE: [feat] 수험자 시험 유의사항 정보 업데이트

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/EyeseeApplication.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/config/SecurityConfig.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/controller/ExamController.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/dto/CheatingStatistic.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/dto/ExamRequestDTO.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/dto/TokenWithUserIdResponseDTO.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/dto/UserDetailResponseDTO.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/entity/CheatingType.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/entity/Exam.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/enums/CheatingTypeEnum.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/repository/CheatingStatisticsRepository.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/repository/ExamRepository.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/service/ExamService.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/service/SessionService.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/utils/CheatingTypeConverter.java

> ex) #6, #26
> 시험 등록 시 On/Off 기능 추가 및 CheatingStatistic 수정

BE: [fix] 시험 등록 시 On/Off 기능 추가 및 CheatingStatistic 수정

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/controller/ExamController.java

> ex) #6
> 능지 이슈로 인한 api endpoint 수정
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

BE: [fix] 세션 내 학생 조회 Endpoint 수정 #6

---

src/ai/main.py

AI: [fix] logic 오류 수정

---

src/frontend/eyesee-admin/src/app/add-exam/page.tsx
src/frontend/eyesee-admin/src/app/dashboard/[examId]/[userId]/page.tsx
src/frontend/eyesee-admin/src/components/addExam/CheatingSetting.tsx
src/frontend/eyesee-admin/src/components/addExam/Step2.tsx
src/frontend/eyesee-admin/src/components/dashBoard/DashBoardSection.tsx
src/frontend/eyesee-admin/src/components/dashBoard/TestInfo.tsx
src/frontend/eyesee-admin/src/components/report/ReportSection.tsx
src/frontend/eyesee-admin/src/components/userDetail/TimeLine.tsx
src/frontend/eyesee-admin/src/constant/monitoring.ts
src/frontend/eyesee-admin/src/types/exam.ts
src/frontend/eyesee-admin/src/types/timeLine.ts

> #66
1. 수험자 단건 조회 타임라인 ui 수정
2. 부정행위 탐지 기준 설정 기능 추가

FE: [feat] 부정행위 탐지 기준 설정 기능 추가

---

src/ai/custom_utils.py
src/ai/detectors.py
src/ai/main.py

AI:[fix] 부정행위 탐지 안되는 버그

---

src/ai/main.py

AI: [fix] 웹소켓 오류

---

src/ai/constants.py
src/ai/detectors.py
src/ai/main.py

AI: [fix] 부정 행위 감도 변경

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/config/AmazonS3Config.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/config/SecurityConfig.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/controller/VideoController.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/service/VideoService.java

> ex) #6,#26
> 부정행위 영상 저장하는 api 구현
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

BE: [Feature] 부정행위 영상 저장 #6, #26

---

.idea/sonarlint/issuestore/0/0/00b2af604a29b7619106f5ba84f18ed5078b84a1
.idea/sonarlint/issuestore/index.pb
.idea/sonarlint/securityhotspotstore/index.pb
.idea/workspace.xml
src/ai/main.py

1. timeozone을 UTC로 보내 데이터베이스에 9시간 빠르게 저장되는 이슈 해결
2. 백엔드에서 받은 데이터가 ENUM : boolean 이어서 dictionary의 Key 값이 대문자인데 update_cheating의 조건은 get (소문자)로 불러와서 부정행위 탐지 로직 자체가 안돌아가던 이슈 해결
3. 1번의 문제를 대충 KTC로 바꾸었다가 +0900 오프셋 붙어서 백엔드에서 못 읽는 현상을 UTC를 KTC로 변환 후 ISO 포맷으로 strftime 메소드 사용하여 포맷 형식 통일

AI: [fix] 백엔 api 오류 수정

---

.idea/sonarlint/issuestore/0/0/00b2af604a29b7619106f5ba84f18ed5078b84a1
.idea/sonarlint/issuestore/3/5/35033099a2dee491ee236da156def7c1e948b312
.idea/sonarlint/issuestore/index.pb
.idea/sonarlint/securityhotspotstore/index.pb
.idea/workspace.xml
src/ai/constants.py

> ex) #이슈번호, #이슈번호
> 민감도가 너무 높아 수치 조정
1. 고개 상하 수정 20 -> 30
2. 눈동자 각도 수정 -> 30
3. 손동작 지속 시간 변경 2초
4. 고개 좌우 각도 수정 20 -> 30

AI: [fix] modify constants

---

src/frontend/eyesee-admin/src/app/report/[examId]/page.tsx
src/frontend/eyesee-admin/src/components/dashBoard/BottomSheet.tsx
src/frontend/eyesee-admin/src/components/report/ReportSection.tsx
src/frontend/eyesee-user/src/apis/video.ts
src/frontend/eyesee-user/src/app/exam-room/page.tsx

> #53 
1. UI 에러 수정
2. 인증헤어 제외하여 video api 호출
3. video 파일 형식, 확장자 수정(webm → mp4)

FE: [fix] 영상 확장자 변경

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/controller/VideoController.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/service/VideoService.java

> ex) #37 
> 동영상 확장자 동적으로 저장시킬 수 있도록 하고, 로그를 추가하여 확인 쉽도록 수정하였습니다.

BE: [Fix] 동영상 확장자 동적 저장 #37

---

src/frontend/eyesee-admin/src/app/dashboard/[examId]/[userId]/page.tsx
src/frontend/eyesee-admin/src/components/dashBoard/DashBoardSection.tsx
src/frontend/eyesee-admin/src/components/dashBoard/UserSection.tsx
src/frontend/eyesee-admin/src/components/report/ReportSection.tsx
src/frontend/eyesee-admin/src/components/userDetail/TimeLine.tsx
src/frontend/eyesee-user/src/app/exam-room/page.tsx

FE: [fix] 디버깅 코드 삭제 및 UI 수정

---

src/backend/Eyesee/src/main/java/com/fortune/eyesee/dto/UserListResponseDTO.java
src/backend/Eyesee/src/main/java/com/fortune/eyesee/service/ExamService.java

BE: [Fix] 대시보드에 시험 코드 추가 #6
